from fastapi import APIRouter, Depends, HTTPException
import uuid
import logging
from google.adk.runners import InMemoryRunner
from google.adk.sessions import InMemorySessionService
from google.genai.types import Content, Part
from google.genai.errors import APIError

from backend.models.request import GenerateRequest
from backend.models.response import GenerateResponse
from backend.security.rate_limiter import limiter
from backend.security.input_validator import InputValidator
from backend.security.api_key_manager import verify_gemini_api_key
from backend.utils.mock_generator import get_mock_study_plan
from agents.orchestrator import app
from utils.railway_graph import RailwayGraph

logger = logging.getLogger(__name__)
router = APIRouter()
validator = InputValidator()
railway = RailwayGraph()
runner = InMemoryRunner(app=app)
session_service = runner.session_service

@router.post("/generate", response_model=GenerateResponse, dependencies=[Depends(limiter.check_rate_limit)])
async def generate_study_plan(req: GenerateRequest, api_key: str = Depends(verify_gemini_api_key)):
    # 1. Input validation & sanitization
    try:
        inputs = validator.validate_generate_request(req.source, req.destination, req.subject, req.module)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
        
    source = inputs["source"]
    destination = inputs["destination"]
    subject = inputs["subject"]
    module = inputs["module"]
    
    # 2. Calculate travel time
    duration, path = railway.calculate_travel_time(source, destination, is_peak=req.is_peak)
    if duration is None or path is None:
        raise HTTPException(status_code=404, detail="Route between specified stations not found.")
        
    # 3. Guardrail: if travel time < 5 mins, return too short
    if duration < 5:
        return GenerateResponse(
            source=source,
            destination=destination,
            duration=duration,
            path=path,
            subject=subject,
            study_plan=None,
            is_too_short=True,
            message=f"Travel time is {duration} minutes. Commute is too short for a study session (minimum 5 minutes required)."
        )
        
    # 4. Invoke ADK Agent Orchestrator
    session_id = str(uuid.uuid4())
    user_id = "commuter"
    
    try:
        # Pre-seed session state with the travel duration and selected module
        await session_service.create_session(
            app_name=runner.app_name,
            user_id=user_id,
            session_id=session_id,
            state={"commute_duration": duration, "selected_module": module}
        )
        
        # User message initiates the syllabus extraction for the requested subject
        user_message = Content(parts=[Part(text=subject)])
        
        # Execute the agent flow
        async for event in runner.run_async(
            user_id=user_id,
            session_id=session_id,
            new_message=user_message
        ):
            pass  # We collect the result from the updated session state
            
        # Retrieve the final state containing the study plan
        updated_session = await session_service.get_session(
            app_name=runner.app_name,
            user_id=user_id,
            session_id=session_id
        )
        study_plan = updated_session.state.get("study_plan")
        
        # Cleanup session to prevent memory leaks
        await session_service.delete_session(
            app_name=runner.app_name,
            user_id=user_id,
            session_id=session_id
        )
        
        if not study_plan:
            raise HTTPException(
                status_code=500,
                detail="Study plan could not be generated by the agents."
            )
            
        return GenerateResponse(
            source=source,
            destination=destination,
            duration=duration,
            path=path,
            subject=subject,
            study_plan=study_plan,
            is_too_short=False,
            message="Study plan generated successfully!"
        )
        
    except APIError as e:
        # Only fall back to offline mode for rate limits (429) or quota errors
        if e.code == 429:
            logger.warning(f"Gemini API rate limit reached (429). Falling back to offline mock planner.")
            mock_plan = get_mock_study_plan(subject, duration, module_filter=module)
            
            # Make sure to clean up session on fallback too
            try:
                await session_service.delete_session(app_name=runner.app_name, user_id=user_id, session_id=session_id)
            except Exception:
                pass
                
            return GenerateResponse(
                source=source,
                destination=destination,
                duration=duration,
                path=path,
                subject=subject,
                study_plan=mock_plan,
                is_too_short=False,
                message="Gemini API limit reached. Loaded offline study plan successfully."
            )
        else:
            logger.error(f"Gemini API error occurred (code={e.code}): {e.message}", exc_info=True)
            # Try session cleanup
            try:
                await session_service.delete_session(app_name=runner.app_name, user_id=user_id, session_id=session_id)
            except Exception:
                pass
            raise HTTPException(status_code=502, detail=f"Gemini API error: {e.message}")
            
    except Exception as e:
        logger.error(f"Unexpected error during study plan generation: {str(e)}", exc_info=True)
        # Try session cleanup
        try:
            await session_service.delete_session(app_name=runner.app_name, user_id=user_id, session_id=session_id)
        except Exception:
            pass
        raise HTTPException(status_code=500, detail=f"Internal Server Error: {str(e)}")
